DELETE  https://3000-rippercode-blogslist-138one36vuq.ws-us108.gitpod.io/api/blogs/65e8f40edd6b55a146759f30
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJpcHBlcnhvbmUiLCJpZCI6IjY1ZGRmODc3ZWViN2VmZWU1MDgxMzkzNSIsImlhdCI6MTcwOTc1NTIxM30.wxCLweKF5Nx-ls515PeHZq6qtRVIBc3qhAYrPLAiguc