POST  https://3000-rippercode-blogslist-138one36vuq.ws-us108.gitpod.io/api/users
Content-Type: application/json

{
    "username": "Ripperxone",
    "name": "diosmar marquez",
    "password": "1asdlashlahf45"
}
