POST https://3000-rippercode-blogslist-138one36vuq.ws-us108.gitpod.io/api/blogs
Content-Type: application/json

{
    "title": "Canonical string reduction",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    "likes": 12
}
